---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Install packages
      community.general.pacman:
        name:
          - networkmanager
          - man
          - reflector
          - curl
          - wget
          - unzip
          - ntp
          - htop
          - vim
          - neovim
          - neofetch
          - ttf-meslo-nerd
          - ttf-nerd-fonts-symbols
          - openssh
          - tlp
          - tmux
        state: present
      become: true




    # CONFIGURE SERVICES
    - name: Enable network manager service
      ansible.builtin.systemd:
        name: NetworkManager
        enabled: true
        state: started
      become: true

    - name: Enable tlp power saving
      ansible.builtin.systemd:
        name: tlp
        enabled: true
        state: started
      become: true

    - name: Enable time sync
      ansible.builtin.systemd:
        name: systemd-timesyncd
        enabled: true
        state: started
      become: true
      notify:
        - Setup ntp




    # FIREWALL
    - name: Install firewall
      community.general.pacman:
        name:
          - ufw
        state: present
      become: true

    - name: Deny all incoming traffic
      ufw:
        rule: deny
        direction: in
      become: true

    - name: Deny all routed traffic
      ufw:
        rule: deny
        direction: routed
      become: true

    - name: Allow all outgoing traffic
      ufw:
        rule: allow
        direction: out
      become: true

    - name: Enable UFW systemd service
      ansible.builtin.systemd:
        name: ufw
        enabled: true
        state: started
      become: true



    # SWAY WAYLAND DISPLAY MANAGER
    - name: Install packages for sway
      community.general.pacman:
        name:
          - polkit
          - sway
          - swayidle
          - swaylock
          - swaybg
          - wmenu
          - foot
          - fuzzel
          - wl-clipboard
          - xdg-desktop-portal-wlr # for screen sharing
        state: present
      become: true



    # EXTRA PACKAGES
    - name: Install extra convencience packages
      community.general.pacman:
        name:
          - noto-fonts
          - firejail
          - firefox
          - arc-gtk-theme
          - papirus-icon-theme
          - base-devel
          - git
          - go
          - make
          - chromium
          - tree
        state: present
      become: true


    # CONFIGURE USER ACCESS
    - name: Add user to groups
      ansible.builtin.user:
        name: "{{ username }}"
        groups: wheel,audio
        append: true
      become: true

    - name: Add wheel to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
        state: present
        regexp: "^%wheel.*NOPASSWD:.*$"
      become: true

    - name: Ensure user directories exist
      file:
        path: "/home/{{ username }}/{{ item }}"
        state: directory
        mode: "0700"
        owner: "{{ username }}"
        group: "{{ username }}"
      become: true
      become_user: "{{ username }}"
      loop:
        - "Downloads"
        - "Documents"


    # MICROCODE UPDATES
    - name: Get CPU information
      command: lscpu
      register: lscpu
      changed_when: false

    - name: Install microcode package for Intel CPUs
      pacman:
        name: intel-ucode
      when: "'GenuineIntel' in lscpu.stdout"
      become: true
      notify: Update GRUB

    - name: Install microcode package for AMD CPUs
      pacman:
        name: amd-ucode
      when: "'AuthenticAMD' in lscpu.stdout"
      become: true
      notify: Update GRUB



    # NEOVIM
    - name: Install packages for neovim config
      community.general.pacman:
        name:
          - ripgrep
          - npm
          - nodejs
          - ttf-meslo-nerd
        state: present
      become: true
      register: register_package

    - name: Update font cache
      command: fc-cache -f -v
      become: true
      when: register_package.changed


    # SSH
    - name: Create user .ssh directory
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ username }}"
        group: "{{ username }}"
      become: true
      become_user: "{{ username }}"

    - name: Generate ssh key-pair
      community.crypto.openssh_keypair:
        path: "/home/{{ username }}/.ssh/id_ed25519"
        type: "ed25519"
      become: true
      become_user: "{{ username }}"

    - name: Disable SSH service
      ansible.builtin.systemd:
        name: sshd
        enabled: false
        state: stopped
      become: true

    - name: Disable SSH in config
      ansible.builtin.blockinfile:
        path: /etc/ssh/ssh_config
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          PermitRootLogin no
          PasswordAuthentication no
          PubkeyAuthentication no
          DenyUsers *
        state: present
        create: false
        mode: "0640"
        owner: "root"
        group: "root"
      become: true


    # KERNEL HARDENING
    - name: Harden kernel
      ansible.builtin.blockinfile:
        path: /etc/sysctl.d/99-hardening.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # protect against SYN flood attacks
          net.ipv4.tcp_syncookies=1

          # protects against time-wait assassination by dropping RST packets for sockets in the time-wait state
          net.ipv4.tcp_rfc1337=1

          # disable commonly exploited SACK
          net.ipv4.tcp_sack=0
          net.ipv4.tcp_dsack=0
          net.ipv4.tcp_fack=0

          # do not leak system time
          net.ipv4.tcp_timestamps=0

          # ignore all ICMP requests to avoid Smurf attacks,
          # make device enumeration more difficult,
          # prevent clock fingerprinting through ICMP timestamps
          net.ipv4.icmp_echo_ignore_all=1

          # enable source validation to protect against IP spoofing
          net.ipv4.conf.all.rp_filter=1
          net.ipv4.conf.default.rp_filter=1

          # disable ICMP redirect acceptance to prevent man in middle
          net.ipv4.conf.all.accept_redirects=0
          net.ipv4.conf.default.accept_redirects=0
          net.ipv4.conf.all.secure_redirects=0
          net.ipv4.conf.default.secure_redirects=0
          net.ipv6.conf.all.accept_redirects=0
          net.ipv6.conf.default.accept_redirects=0
          net.ipv4.conf.all.send_redirects=0
          net.ipv4.conf.default.send_redirects=0

          # disable source routing to disable network traffic redirect
          net.ipv4.conf.all.accept_source_route=0
          net.ipv4.conf.default.accept_source_route=0
          net.ipv6.conf.all.accept_source_route=0
          net.ipv6.conf.default.accept_source_route=0

          # disable ipv6 router advertising
          net.ipv6.conf.all.accept_ra=0
          net.ipv6.conf.default.accept_ra=0

          # disables debugfs to prevent exposing sensitive kernel information
          debugfs=off

          # disables obsolete vsyscalls
          vsyscall=none

          # Protect kernel pointers from unprivileged users
          kernel.kptr_restrict = 1

          # Restrict ptrace to own processes (prevents process snooping)
          kernel.yama.ptrace_scope = 1

          # Filesystem
          fs.suid_dumpable = 0
          fs.protected_hardlinks = 1
          fs.protected_symlinks = 1
          fs.protected_fifos = 2
          fs.protected_regular = 2

        state: present
        create: true
        mode: "0600"
        owner: root
        group: root
      become: true


    - name: Configure journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: "SystemMaxUse=100M"
        state: present
        regexp: "^#SystemMaxUse="
      become: true
      notify: Restart journald



    # KUBERNETES
    - name: Install k8s packages
      pacman:
        name:
          - docker
          - kubectl
          - helm
          - minikube
          - bash-completion
          - kind
        state: present
      become: true

    - name: Ensure group docker exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
      become: true
      notify: Restart docker service

    # CONFIGURE ROOTLESS DOCKER
    # (!) without, user can escalate to host root
    # https://wiki.archlinux.org/title/Docker#Rootless_Docker_daemon
    - name: Ensure subuid entry exists for rootless user
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: "{{ ansible_user_id }}:100000:65536"
        regexp: "^{{ ansible_user_id }}:"
        create: yes
        state: present
      become: true

    - name: Ensure subgid entry exists for rootless user
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: "{{ ansible_user_id }}:100000:65536"
        regexp: "^{{ ansible_user_id }}:"
        create: yes
        state: present
      become: true

    - name: Enable Docker rootless service as user unit
      ansible.builtin.command:
        cmd: "systemctl --user enable --now docker.service"

    - name: Create Docker rootless context
      ansible.builtin.command:
        cmd: >
          docker context create rootless --description "Rootless mode"
          --docker "host=unix:///run/user/{{ lookup('ansible.builtin.env','UID') }}/docker.sock"
      ignore_errors: true

    - name: Set Docker rootless context as current
      ansible.builtin.command:
        cmd: "docker context use rootless"



    # CONFIGURE AUDIT TOOLS
    - name: Install audit packages
      community.general.pacman:
        name:
          # scanning
          - rkhunter
          - clamav
          # system audit
          - lynis
          # audit logging
          - audit
          # apparmor
          - apparmor
          - python-notify2
          - python-psutil
          # usb guard
          - usbguard
          # vpn
          - openvpn
        state: present
      become: true

    # ssh
    - name: Disable password SSH login
      ansible.builtin.blockinfile:
        path: /etc/rkhunter.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # outdated commands that have been replaced by shell scripts
          SCRIPTWHITELIST=/usr/bin/egrep
          SCRIPTWHITELIST=/usr/bin/fgrep
          SCRIPTWHITELIST=/usr/bin/ldd

          # systemd files
          ALLOWHIDDENFILE=/etc/.updated
          ALLOWHIDDENFILE=/usr/share/man/man5/.k5identity.5.gz
          ALLOWHIDDENFILE=/usr/share/man/man5/.k5login.5.gz

        state: present
        create: false
        mode: "0600"
        owner: "root"
        group: "root"
      become: true

    # hibernate
    - name: Disable system hibernate for LUKS encryption compatability
      ansible.builtin.copy:
        dest: /etc/systemd/sleep.conf.d/disable-sleep.conf
        content: |
          [Sleep]
          AllowSuspend=yes
          AllowHibernation=no
          AllowHybridSleep=no
          AllowSuspendThenHibernate=no
        owner: root
        group: root
        mode: '0640'
      become: true

    # PAM lockout
    - name: Configure PAM base package lockout behaviour
      # unlock after failed attempts: faillock --user username --reset
      ansible.builtin.copy:
        dest: /etc/security/faillock.conf
        content: |
          deny=4                  # limited tries
          unlock_time=3600        # 1h lock
          even_deny_root=true     # root is already locked with passwd --lock root, extra measure
          fail_interval=900       # only count failures within 15 min
          dir=/var/lib/faillock   # persist reboots
        owner: root
        group: root
        mode: '0640'
      become: true

    # PAM limits
    - name: Configure PAM limits
      become: true
      ansible.builtin.copy:
        dest: /etc/security/limits.d/99-dev.conf
        owner: root
        group: root
        mode: '0640'
        content: |
          *           soft    priority   0            # Neutral niceness
          *           hard    nproc      4096         # Prevent fork-bombs
          root        hard    nproc      65536        # Allow root to spawn many processes
          *           hard    nofile     65535        # Open file descriptors limit
          *           soft    nofile     8192         # Open file descriptors (soft limit)
          *           soft    core       0            # Disable core dumps
          *           hard    core       0
          *           hard    nice       -19          # Prevent non-root users from low priority processes
          root        hard    nice       -20          # Root can run at minimal niceness

    # auditd - https://wiki.archlinux.org/title/Audit_framework
    - name: Enable auditd service
      ansible.builtin.systemd:
        name: auditd
        enabled: true
        state: started
      become: true

    - name: Configure audit rules
      # add manually first
      # list:
      # auditctl -l
      #
      # create:
      # auditctl -a always,exit -F arch=b64 -F path=/etc/passwd -F perm=rwxa
      #
      # verify:
      # augenrules --check
      # augenrules --load
      #
      # search:
      # ausearch -p 1
      #
      # audit:
      # aureport -n
      become: true
      ansible.builtin.copy:
        dest: /etc/audit/rules.d/mycustom.rules
        owner: root
        group: root
        mode: '0640'
        content: |
          # file
          -a always,exit -F arch=b64 -F path=/etc/passwd -F perm=rwxa
          -a always,exit -F arch=b64 -F path=/etc/shadow -F perm=rwxa
          -a always,exit -F arch=b64 -F path=/etc/group -F perm=rwxa
          -a always,exit -F arch=b64 -F path=/etc/ssh/sshd_config -F perm=rwxa
          -a always,exit -F arch=b64 -F path=/etc/sudoers -F perm=rwxa
          -a always,exit -F arch=b64 -F path=/etc/fstab -F perm=rwxa

          # dir
          -a always,exit -F arch=b64 -F dir=/boot
          -a always,exit -F arch=b64 -F dir=/etc/apparmor.d
          -a always,exit -F arch=b64 -F dir=/etc/network
          -a always,exit -F arch=b64 -F dir=/etc/sudoers.d
          -a always,exit -F arch=b64 -F dir=/etc/security
          -a always,exit -F arch=b64 -F dir=/etc/cron.d
          -a always,exit -F arch=b64 -F dir=/etc/cron.daily
          -a always,exit -F arch=b64 -F dir=/etc/cron.hourly
          -a always,exit -F arch=b64 -F dir=/etc/cron.monthly
          -a always,exit -F arch=b64 -F dir=/etc/cron.weekly

          # exe
          -a always,exit -F arch=b64 -F exe=/bin/su
          -a always,exit -F arch=b64 -F exe=/usr/bin/passwd
          -a always,exit -F arch=b64 -F exe=/usr/sbin/usermod
          -a always,exit -F arch=b64 -F exe=/usr/sbin/chsh
          -a always,exit -F arch=b64 -F exe=/usr/sbin/useradd
          -a always,exit -F arch=b64 -F exe=/usr/bin/sudo
          -a always,exit -F arch=b64 -F exe=/usr/sbin/sudo
          -a always,exit -F arch=b64 -F exe=/bin/chmod
          -a always,exit -F arch=b64 -F exe=/bin/chown

    # allow user to see audit logs
    - name: Ensure audit group exists
      group:
        name: audit
        state: present

    - name: Add user to audit group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: audit
        append: true
      become: true

    - name: Configure audit logging behaviour
      become: true
      ansible.builtin.copy:
        dest: /etc/audit/auditd.conf
        owner: root
        group: root
        mode: '0640'
        content: |
          log_group = audit

    # apparmor
    - name: Install apparmor packages
      community.general.pacman:
        name:

        state: present
      become: true

    - name: Enable apparmor service
      ansible.builtin.systemd:
        name: apparmor
        enabled: true
        state: started
      become: true

    - name: Configure audit logging behaviour
      become: true
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.config/autostart/apparmor-notify.desktop"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0640'
        content: |
          log_group = audit
          [Desktop Entry]
          Type=Application
          Name=AppArmor Notify
          Comment=Receive on-screen notifications of AppArmor denials
          TryExec=aa-notify
          Exec=aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log
          StartupNotify=false
          NoDisplay=true

    # TODO
    # - name: Configure apparmor profiles
    #   # https://wiki.archlinux.org/title/AppArmor
    #   # aa-enabled
    #   # aa-status
    #   # aa-teardown ---> disables apparmor profiles
    #   become: true
    #   ansible.builtin.copy:
    #     dest: /etc/audit/rules.d/monkey.rules
    #     owner: root
    #     group: root
    #     mode: '0640'
    #     content: |
    #       # file
    #       -a always,exit -F arch=b64 -F path=/etc/passwd -F perm=rwxa

    # TODO: usbguard
    # https://wiki.archlinux.org/title/USBGuard
    # /etc/usbguard/rules.conf

    # TODO: arch-specific dotfiles -> dotfiles repo
    # TODO: dotfiles makefile, dot- prefix

  handlers:
    - name: Setup ntp
      ansible.builtin.command: timedatectl set-ntp true
      become: true

    - name: Restart journald
      ansible.builtin.systemd:
        name: systemd-journald
        enabled: true
        state: restarted
      become: true




